General updates
glassboard-dev/gl-vscode-template-arm pull request #9
Opened 2024-08-26 18:26 UTC by devinjaenicke

2024-08-26 19:08 UTC, devinjaenicke commented on .github/workflows/release.yml
>      - name: Setup & Build - DEBUG
It builds both the release and debug variants.

2024-08-26 19:08 UTC, chadcoonsGB submitted a review, later dismissed

2024-08-26 19:38 UTC, lukewelchGB requested changes

2024-08-26 19:38 UTC, lukewelchGB commented on README_TEMPLATE.md
> +-   [Clang-Format](https://clang.llvm.org/docs/ClangFormat.html)
I think we should just include pre-commit, since it already includes clang-format. But I'll leave this up to you.

2024-08-27 13:09 UTC, lukewelchGB approved these changes

2024-09-25 14:43 UTC, drewwestrick approved these changes

2024-09-25 14:43 UTC, drewwestrick commented on cmake/flags.cmake
Just want to confirm you want all warnings to show as errors.

2024-09-25 14:43 UTC, drewwestrick commented on gcovr.cfg
If this isn't part of the upload artifact, it might be nice to default add that so you can see the code coverage report.

2025-04-30 12:39 UTC, merged